/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.Escalao;
import backend.Evento;
import backend.ListaEscalao;
import backend.ListaEventos;
import backend.ListaPavilhao;
import backend.Pavilhao;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author cataf
 */
public class AdicionarEvento extends javax.swing.JFrame {
    private ListaEscalao lista_geral_esc= new ListaEscalao();
    private ListaEventos lista_eventos=new ListaEventos();
    private ListaPavilhao lista_pavilhao=new ListaPavilhao();
    /**
     * Creates new form AdicionarEvento
     */
    public AdicionarEvento() {
        initComponents();
        carregarTipoEvento();
        carregarListaEscaloes();
        carregarPavilhoes();
        //Mostra a centralização da janela
        this.setLocationRelativeTo(null);
    }
    
    private void carregarTipoEvento(){
        comboTipo.removeAllItems();
        comboTipo.addItem("Jogo");
        comboTipo.addItem("Treino");
    }
    
    private void carregarListaEscaloes(){
        comboEquipa.removeAllItems();
        for (Escalao esc : lista_geral_esc.listagemEscalao()){
            String nome =esc.getNome();
            String id =esc.getId_equipa();
            String item=String.join("-", id, nome);
            comboEquipa.addItem(item);   
        }
    }
    
    private void carregarPavilhoes(){
        comboPavilhao.removeAllItems();
        for (Pavilhao pv : lista_pavilhao.listagemPavilhoes()){
            String id =pv.getIdPavilhao();
            String nome=pv.getNome();
            String item2=String.join("-", id, nome);
            comboPavilhao.addItem(item2);   
        }
    }
      private void adicionarEvento() throws ListaEventos.EventoNaoExistenteException, ListaEscalao.EscalaoNaoExistenteException{
        if(txtNome.getText().isEmpty()|| comboTipo.getSelectedItem()==null || comboEquipa.getSelectedItem()==null|| comboPavilhao.getSelectedItem()==null || txtDia.getDate()==null|| txtHora.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Preencha todos os campos obrigatórios!");       
        }else{
            String nome=txtNome.getText();
            String descricao=txtDescricao.getText();
      
            
            String item = String.valueOf(comboPavilhao.getSelectedItem());
            String[] valores=item.split("-");
            String id_pavilhao=valores[0];
            Pavilhao pavilhao=lista_pavilhao.getPavilhao(id_pavilhao);
            
            String resultadoTipo=String.valueOf(comboTipo.getSelectedItem());
            String tipo=new String();
            if(resultadoTipo.equals("Jogo")){
                tipo="J";
            }else if(resultadoTipo.equals("Treino")){
                tipo="T";
            }
            
            LocalDate dia= txtDia.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            String hora=txtHora.getText();
            
            String item2 = String.valueOf(comboEquipa.getSelectedItem());
            String[] valores2=item2.split("-");
            String id_escalao=valores2[0];
            Escalao escalao=lista_geral_esc.getEscalao(id_escalao);
            
            
            if(comboTipo.getSelectedItem().equals("Jogo")){
                Evento e=new Evento(nome,descricao, pavilhao, dia, hora, escalao, tipo);
                lista_eventos.adicionarEventos(e);
               JOptionPane.showMessageDialog(this, "Jogo registado com sucesso!");
            }else if(comboTipo.getSelectedItem().equals("Treino")){
                Evento e=new Evento(nome,descricao, pavilhao, dia, hora, escalao, tipo);
                lista_eventos.adicionarEventos(e);
                JOptionPane.showMessageDialog(this, "Treino registado com sucesso!");
            }
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtDescricao = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        comboEquipa = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        comboPavilhao = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtDia = new com.toedter.calendar.JDateChooser();
        txtNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        imagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(253, 244, 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDescricao.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });
        jPanel2.add(txtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 300, -1));

        txtHora.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jPanel2.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 300, -1));

        jButton1.setBackground(new java.awt.Color(255, 236, 52));
        jButton1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jButton1.setText("ADICIONAR EVENTO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 201, -1));

        jButton2.setBackground(new java.awt.Color(255, 236, 52));
        jButton2.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 201, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel1.setText("Descricão:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 131, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel2.setText("Tipo do evento:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 175, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel3.setText("Escalão e Género:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 126, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel4.setText("Localização:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 112, -1));

        comboTipo.setBackground(new java.awt.Color(255, 255, 204));
        comboTipo.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(comboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 300, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel6.setText("Hora (formato hh:mm):");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 150, -1));

        comboEquipa.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        comboEquipa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(comboEquipa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 300, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ADICIONAR EVENTO");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        comboPavilhao.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        comboPavilhao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboPavilhao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPavilhaoActionPerformed(evt);
            }
        });
        jPanel2.add(comboPavilhao, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 300, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel8.setText("Dia:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 112, -1));
        jPanel2.add(txtDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 300, -1));

        txtNome.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel2.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 300, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel5.setText("Nome do evento:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 118, 131, -1));

        imagemFundo.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        imagemFundo.setForeground(new java.awt.Color(255, 255, 255));
        imagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem Título-1.png"))); // NOI18N
        jPanel2.add(imagemFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 520));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            adicionarEvento();
            dispose();
        } catch (ListaEventos.EventoNaoExistenteException ex) {
            Logger.getLogger(AdicionarEvento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ListaEscalao.EscalaoNaoExistenteException ex) {
            Logger.getLogger(AdicionarEvento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void comboPavilhaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPavilhaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPavilhaoActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboEquipa;
    private javax.swing.JComboBox<String> comboPavilhao;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel imagemFundo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtDescricao;
    private com.toedter.calendar.JDateChooser txtDia;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
