/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.Atleta;
import backend.Escalao;
import backend.ListaEscalao;
import backend.ListaUtilizadores;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author cataf
 */
public class DadosAtleta extends javax.swing.JFrame {
    private ListaUtilizadores lista_geral_users= new ListaUtilizadores();
    private ListaEscalao lista_geral_esc= new ListaEscalao();
    private Atleta a;
    /**
     * Creates new form RegistarAtleta
     */
    public DadosAtleta(Atleta a) {
        this.a=a;
        initComponents();
        
        //Mostra a centralização da janela
        this.setLocationRelativeTo(null);
        
        //preencher caixas
        txtNome.setText(a.getNome());
        if(lista_geral_users.getEquipaAtleta(a)==null){
                String resul="Sem equipa";
                txtEscalao.setText(resul);
            }else{
                ArrayList<Escalao> equipas = lista_geral_users.getEquipaAtleta(a);
                ArrayList<String> nome_eq= new ArrayList(); 
                String nome;
                for(int i=0; i<equipas.size(); i++){
                    Escalao e = equipas.get(i);
                    nome=e.getNome();
                    nome_eq.add(nome);                  
                }
                String resul = String.join(", ", nome_eq);
                txtEscalao.setText(resul);
                
            }
        //txtEscalao.setText(a.getEscalao().getId_escalao());
        
        txtCipa.setText(a.getCipa());
        txtDataNasc.setText(String.valueOf(a.getDataNasc()));
        txtContacto.setText(String.valueOf(a.getContactoTlm()));
        txtPass.setText(a.getPassword());
        
        
    }
    
    private void guardar() throws ListaEscalao.EscalaoNaoExistenteException{  
        lista_geral_users.removerAtleta(a);
        Atleta atleta =new Atleta();
        if (txtNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza o nome!");            
            txtNome.requestFocus();
            return;
        }else{
            atleta.setNome(txtNome.getText());
        }
        /*
        if (txtUsername.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza o username!");            
            txtUsername.requestFocus();
            return;
        }else{
            atleta.setUsername(txtUsername.getText());
        }
        
        if (txtEscalao.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza o escalao!");            
            txtEscalao.requestFocus();
            return;
        }else{
            atleta.setEscalao(lista_geral_esc.getEscalao(txtEscalao.getText()));
        }*/
        
        if (txtCipa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza o cipa!");            
            txtCipa.requestFocus();
            return;
        }else{
            atleta.setCipa(txtCipa.getText());
            atleta.setCipa(txtCipa.getText());
        }
        
        if (txtContacto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza o numero do seu telemovel!");            
            txtContacto.requestFocus();
            return;
        }else{
            atleta.setContactoTlm(Integer.parseInt(txtContacto.getText()));
        }
        
        if (txtPass.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza uma palavra passe!");            
            txtPass.requestFocus();
            return;
        }else{
            atleta.setPassword(txtPass.getText());
        }

        LocalDate data = LocalDate.parse(txtDataNasc.getText());
        atleta.setDataNasc(data);
        lista_geral_users.adicionarAtleta(atleta);
        JOptionPane.showMessageDialog(this, "Dados alterados com sucesso!");
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDataNasc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        txtCipa = new javax.swing.JTextField();
        checkVerPass = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtEscalao = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtContacto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        alterarAtletaBtn = new javax.swing.JButton();
        removerAtletaBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(398, 522));
        setSize(new java.awt.Dimension(398, 520));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDataNasc.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataNascActionPerformed(evt);
            }
        });
        getContentPane().add(txtDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 290, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel9.setText("Contacto:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 112, -1));

        txtNome.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 290, -1));

        txtPass.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 290, -1));

        txtCipa.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtCipa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCipaActionPerformed(evt);
            }
        });
        getContentPane().add(txtCipa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 290, -1));

        checkVerPass.setBackground(new java.awt.Color(255, 236, 52));
        checkVerPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkVerPassActionPerformed(evt);
            }
        });
        getContentPane().add(checkVerPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 21, 20));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel1.setText("Password:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 131, -1));

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel11.setText("Data de nascimento:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 175, -1));

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel12.setText("Escalão:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 63, -1));

        txtEscalao.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        getContentPane().add(txtEscalao, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 290, -1));

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel13.setText("Cipa:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 131, -1));

        txtContacto.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        getContentPane().add(txtContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 290, -1));

        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel14.setText("Nome:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 131, -1));

        jButton3.setBackground(new java.awt.Color(255, 236, 52));
        jButton3.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jButton3.setText("CANCELAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 170, -1));

        alterarAtletaBtn.setBackground(new java.awt.Color(255, 236, 52));
        alterarAtletaBtn.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        alterarAtletaBtn.setText("ALTERAR DADOS");
        alterarAtletaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarAtletaBtnActionPerformed(evt);
            }
        });
        getContentPane().add(alterarAtletaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        removerAtletaBtn.setBackground(new java.awt.Color(255, 236, 52));
        removerAtletaBtn.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        removerAtletaBtn.setText("REMOVER ATLETA");
        removerAtletaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerAtletaBtnActionPerformed(evt);
            }
        });
        getContentPane().add(removerAtletaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 140, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("DADOS DO ATLETA");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 207, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem Título-1.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataNascActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void txtCipaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCipaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCipaActionPerformed

    private void checkVerPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkVerPassActionPerformed
        if(checkVerPass.isSelected()){
            txtPass.setEchoChar((char)0);
        }else{
            txtPass.setEchoChar('•');
        }
    }//GEN-LAST:event_checkVerPassActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void alterarAtletaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarAtletaBtnActionPerformed
        try {
            guardar();
        } catch (ListaEscalao.EscalaoNaoExistenteException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
        dispose();
    }//GEN-LAST:event_alterarAtletaBtnActionPerformed

    private void removerAtletaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerAtletaBtnActionPerformed
        lista_geral_users.removerAtleta(a);
        JOptionPane.showMessageDialog(this, "Atleta removido com sucesso!");
        dispose();
    }//GEN-LAST:event_removerAtletaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistarAtleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistarAtleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistarAtleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistarAtleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistarAtleta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarAtletaBtn;
    private javax.swing.JCheckBox checkVerPass;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton removerAtletaBtn;
    private javax.swing.JTextField txtCipa;
    private javax.swing.JTextField txtContacto;
    private javax.swing.JTextField txtDataNasc;
    private javax.swing.JTextField txtEscalao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
