/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.Atleta;
import backend.Escalao;
import backend.ListaUtilizadores;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cataf
 */
public class GestaoAtletas extends javax.swing.JFrame {    
    private DefaultTableModel modelAtletas;
    private ListaUtilizadores lista_geral= new ListaUtilizadores();
    /**
     * Creates new form GestaoAtletas
     */
    public GestaoAtletas() {
        initComponents();
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);   
        modelAtletas = (DefaultTableModel) tabelaAtletas.getModel();       
        preencheTabela();
        
        //aparecer texto ao passar cursor em cima
        iconAtletas.setToolTipText("Atletas");       
        UIManager.put("ToolTip.background", Color.WHITE);
        UIManager.put("ToolTip.foreground", Color.BLACK);
        UIManager.put("ToolTip.font", new Font("SansSerif", Font.BOLD, 14));
        
        //aparecer texto ao passar cursor em cima
        iconCalendario.setToolTipText("Calendário");       
        UIManager.put("ToolTip.background", Color.WHITE);
        UIManager.put("ToolTip.foreground", Color.BLACK);
        UIManager.put("ToolTip.font", new Font("SansSerif", Font.BOLD, 14));
        
        //aparecer texto ao passar cursor em cima
        iconGestaoTeC.setToolTipText("Treinadores e Colaboradores");       
        UIManager.put("ToolTip.background", Color.WHITE);
        UIManager.put("ToolTip.foreground", Color.BLACK);
        UIManager.put("ToolTip.font", new Font("SansSerif", Font.BOLD, 14));
        
        //aparecer texto ao passar cursor em cima
        iconPagar.setToolTipText("Registar pagamento de quota");       
        UIManager.put("ToolTip.background", Color.WHITE);
        UIManager.put("ToolTip.foreground", Color.BLACK);
        UIManager.put("ToolTip.font", new Font("SansSerif", Font.BOLD, 14));
        
        //aparecer texto ao passar cursor em cima
        iconSair.setToolTipText("Sair");       
        UIManager.put("ToolTip.background", Color.WHITE);
        UIManager.put("ToolTip.foreground", Color.BLACK);
        UIManager.put("ToolTip.font", new Font("SansSerif", Font.BOLD, 14));
    }

    private void preencheTabela() {
        modelAtletas.setRowCount(0); //especifica o nr de linhas na tabela
        for (int index = 0; index < lista_geral.listagemAtletas().size(); index++) {
            Atleta a = lista_geral.listagemAtletas().get(index); 
            if(lista_geral.getEquipaAtleta(a)==null){
                String resul="Sem equipa";
                modelAtletas.addRow(new Object[]{a.getCipa(), a.getNome(),resul, a.getContactoTlm(), a.getDataNasc()});
            }else{
                ArrayList<Escalao> equipas = lista_geral.getEquipaAtleta(a);
                ArrayList<String> nome_eq= new ArrayList(); 
                String nome;
                for(int i=0; i<equipas.size(); i++){
                    Escalao e = equipas.get(i);
                    nome=e.getNome();
                    nome_eq.add(nome);                  
                }
                String resul = String.join(",", nome_eq);
                modelAtletas.addRow(new Object[]{a.getCipa(), a.getNome(),resul, a.getContactoTlm(), a.getDataNasc()});
            }
            
        }
        tabelaAtletas.setModel(modelAtletas);
    }
    
    private void procurar(){
        String user =txtProcura.getText();
        ArrayList <Atleta> listaAtletas = new ArrayList<>();
        listaAtletas = lista_geral.listagemAtletas();
        
        boolean encontrou =false;
        
        for (Atleta a : listaAtletas){
            if(a.getCipa().equals(user)){
                DadosAtleta da = new DadosAtleta(a);
                da.setVisible(true);
                txtProcura.setText("");
                encontrou=true;
            }     
        }
        
        if(encontrou==false){
            JOptionPane.showMessageDialog(this, "Este atleta não existe!");
        }   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconAtletas = new javax.swing.JLabel();
        iconCalendario = new javax.swing.JLabel();
        iconSair = new javax.swing.JLabel();
        iconGestaoTeC = new javax.swing.JLabel();
        iconPagar = new javax.swing.JLabel();
        registarAtletaBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAtletas = new javax.swing.JTable();
        pesquisaBtn = new javax.swing.JButton();
        txtProcura = new javax.swing.JTextField();
        atualizarBtn = new javax.swing.JButton();
        atualizarBtn1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconAtletas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pngwing.com (2).png"))); // NOI18N
        iconAtletas.setText("jLabel1");
        getContentPane().add(iconAtletas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 60));

        iconCalendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calendario.png"))); // NOI18N
        iconCalendario.setText("jLabel2");
        iconCalendario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconCalendarioMouseClicked(evt);
            }
        });
        getContentPane().add(iconCalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 50, 60));

        iconSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar.png"))); // NOI18N
        iconSair.setText("jLabel3");
        iconSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconSairMouseClicked(evt);
            }
        });
        getContentPane().add(iconSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 700, 50, -1));

        iconGestaoTeC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/coach.png"))); // NOI18N
        iconGestaoTeC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconGestaoTeCMouseClicked(evt);
            }
        });
        getContentPane().add(iconGestaoTeC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 50, -1));

        iconPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_quotas.png"))); // NOI18N
        iconPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconPagarMouseClicked(evt);
            }
        });
        getContentPane().add(iconPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 60, -1));

        registarAtletaBtn.setBackground(new java.awt.Color(255, 236, 52));
        registarAtletaBtn.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        registarAtletaBtn.setText("Registar Atleta");
        registarAtletaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registarAtletaBtnMouseClicked(evt);
            }
        });
        registarAtletaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registarAtletaBtnActionPerformed(evt);
            }
        });
        getContentPane().add(registarAtletaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 770, -1, -1));

        tabelaAtletas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CIPA", "NOME", "EQUIPA", "CONTACTO", "DATA NASCIMENTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaAtletas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 730, 610));

        pesquisaBtn.setBackground(new java.awt.Color(255, 236, 52));
        pesquisaBtn.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        pesquisaBtn.setText("Pesquisar");
        pesquisaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaBtnActionPerformed(evt);
            }
        });
        getContentPane().add(pesquisaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 770, -1, -1));

        txtProcura.setBackground(new java.awt.Color(204, 204, 204));
        txtProcura.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtProcura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProcuraActionPerformed(evt);
            }
        });
        getContentPane().add(txtProcura, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 770, 220, -1));

        atualizarBtn.setBackground(new java.awt.Color(255, 236, 52));
        atualizarBtn.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        atualizarBtn.setText("Atualizar");
        atualizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(atualizarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 70, -1, -1));

        atualizarBtn1.setBackground(new java.awt.Color(255, 236, 52));
        atualizarBtn1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        atualizarBtn1.setText("Gestão Escalões");
        atualizarBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(atualizarBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GESTÃO DE ATLETAS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 310, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background_mais pequeno.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registarAtletaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registarAtletaBtnActionPerformed
        
    }//GEN-LAST:event_registarAtletaBtnActionPerformed

    private void pesquisaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaBtnActionPerformed
        if(txtProcura.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Introduza o atleta que deseja visualizar!"); 
        }else{
            procurar();
        }     
    }//GEN-LAST:event_pesquisaBtnActionPerformed

    private void iconSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconSairMouseClicked
        /*PaginaInicial pg = new PaginaInicial();               
        pg.setVisible(true); */
        dispose();
    }//GEN-LAST:event_iconSairMouseClicked

    private void iconCalendarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconCalendarioMouseClicked
        dispose();
        Calendario c = new Calendario();
        c.setVisible(true);
    }//GEN-LAST:event_iconCalendarioMouseClicked

    private void registarAtletaBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registarAtletaBtnMouseClicked
        RegistarAtleta ra = new RegistarAtleta();
        ra.setVisible(true);
    }//GEN-LAST:event_registarAtletaBtnMouseClicked

    private void atualizarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarBtnActionPerformed
        preencheTabela();
    }//GEN-LAST:event_atualizarBtnActionPerformed

    private void atualizarBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarBtn1ActionPerformed
        GestaoEscaloes ge = new GestaoEscaloes();
        ge.setVisible(true);
    }//GEN-LAST:event_atualizarBtn1ActionPerformed

    private void iconGestaoTeCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconGestaoTeCMouseClicked
        dispose();
        GestaoTreinadoresColaboradores gtc = new GestaoTreinadoresColaboradores();
        gtc.setVisible(true);
    }//GEN-LAST:event_iconGestaoTeCMouseClicked

    private void iconPagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconPagarMouseClicked
        dispose();
        RegistarQuota rq = new RegistarQuota();
        rq.setVisible(true);
    }//GEN-LAST:event_iconPagarMouseClicked

    private void txtProcuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProcuraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProcuraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestaoAtletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestaoAtletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestaoAtletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestaoAtletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestaoAtletas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarBtn;
    private javax.swing.JButton atualizarBtn1;
    private javax.swing.JLabel iconAtletas;
    private javax.swing.JLabel iconCalendario;
    private javax.swing.JLabel iconGestaoTeC;
    private javax.swing.JLabel iconPagar;
    private javax.swing.JLabel iconSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pesquisaBtn;
    private javax.swing.JButton registarAtletaBtn;
    private javax.swing.JTable tabelaAtletas;
    private javax.swing.JTextField txtProcura;
    // End of variables declaration//GEN-END:variables
}
