/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.Administrador;
import backend.Colaborador;
import backend.ListaUtilizadores;
import backend.Utilizador;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author cataf
 */
public class Login extends javax.swing.JFrame {
    private ListaUtilizadores lista_geral= new ListaUtilizadores();
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        //Mostra a centralização da janela
        this.setLocationRelativeTo(null);
    //jPanel1.setBackground(new Color(255,255,102,123));
    //painelfundo.setBorder(new EmptyBorder(10,10,10,10));
        
    }
    
    private void iniciar() throws ListaUtilizadores.UtilizadorNaoExistenteException{
        //ArrayList<Colaborador> lista_c = lista_geral.listagemColaboradores();
        //ArrayList<Administrador> lista_a = lista_geral.listagemAdmin();
        if (txtUser.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza o nome de utilizador!");            
            txtUser.requestFocus();
            return;
        }
        
        if (txtPass.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Introduza a password!");
            txtPass.requestFocus();
            return;
        }   
        //saber se o username introduzido corresponde a algum utilizador
        if(lista_geral.getColaborador(txtUser.getText())!=null || lista_geral.getAdmin(txtUser.getText())!=null){
            //se o utilizador for colaborador
            if(lista_geral.getColaborador(txtUser.getText())!=null){
                Colaborador c = lista_geral.getColaborador(txtUser.getText());
                if(c.getPassword().equals(txtPass.getText())){
                    PaginaInicial pg = new PaginaInicial(c);               
                    pg.setVisible(true);
                }else{
                    JOptionPane.showMessageDialog(this, "Palavra passe incorreta!");
                }
            }else{
                //se o utilizador for admin
                Administrador a = lista_geral.getAdmin(txtUser.getText());
                if(a.getPassword().equals(txtPass.getText())){
                    PaginaInicial pg = new PaginaInicial(a);               
                    pg.setVisible(true);
                }else{
                    JOptionPane.showMessageDialog(this, "Palavra passe incorreta!");
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Este username não corresponde com nenhum existente!"); 
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        sairBtn = new javax.swing.JButton();
        entrarBtn = new javax.swing.JButton();
        labelPass = new javax.swing.JLabel();
        checkVerPass = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("LOGIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, -1));

        labelUsername.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelUsername.setText("Username:");
        getContentPane().add(labelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, -1));

        txtUser.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 200, -1));

        txtPass.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 200, -1));

        sairBtn.setBackground(new java.awt.Color(0, 0, 0));
        sairBtn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        sairBtn.setForeground(new java.awt.Color(255, 255, 255));
        sairBtn.setText("Sair");
        sairBtn.setBorderPainted(false);
        sairBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairBtnActionPerformed(evt);
            }
        });
        getContentPane().add(sairBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 80, -1));

        entrarBtn.setBackground(new java.awt.Color(0, 0, 0));
        entrarBtn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        entrarBtn.setForeground(new java.awt.Color(255, 255, 255));
        entrarBtn.setText("Entrar");
        entrarBtn.setBorderPainted(false);
        entrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(entrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, 80, -1));

        labelPass.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelPass.setText("Password:");
        getContentPane().add(labelPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, -1));

        checkVerPass.setBackground(new java.awt.Color(252, 220, 3));
        checkVerPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkVerPassActionPerformed(evt);
            }
        });
        getContentPane().add(checkVerPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 20, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background-abc.jpeg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairBtnActionPerformed
        dispose();
    }//GEN-LAST:event_sairBtnActionPerformed

    private void entrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarBtnActionPerformed
        try {
            iniciar();
        } catch (ListaUtilizadores.UtilizadorNaoExistenteException ex) {
            //Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
       /*
        Utilizador u= new Utilizador();
        PaginaInicial pg = new PaginaInicial(u);               
        pg.setVisible(true);*/
    }//GEN-LAST:event_entrarBtnActionPerformed

    private void checkVerPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkVerPassActionPerformed
        if(checkVerPass.isSelected()){
            txtPass.setEchoChar((char)0);
        }else{
            txtPass.setEchoChar('•');
        }
    }//GEN-LAST:event_checkVerPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkVerPass;
    private javax.swing.JButton entrarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelPass;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JButton sairBtn;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
